### ISSUE TITLE
No such file or directory: '/root/workspace/ROCm/Tensile/repo/Tensile/Source/SolutionMapper.h'

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/Tensile#1414]
develop, commit=243fda774b8da1df23bc7b3ca895f791edf73466

```
################################################################################
# Finish Analysing data to /root/workspace/ROCm/Tensile/dgemm_007-9-asm in 1638.883s
################################################################################


Traceback (most recent call last):
  File "../repo/Tensile/bin/Tensile", line 36, in <module>
    Tensile.main()
  File "/root/workspace/ROCm/Tensile/repo/Tensile/Tensile.py", line 282, in main
    Tensile(sys.argv[1:])
  File "/root/workspace/ROCm/Tensile/repo/Tensile/Tensile.py", line 239, in Tensile
    executeStepsInConfig(config)
  File "/root/workspace/ROCm/Tensile/repo/Tensile/Tensile.py", line 85, in executeStepsInConfig
    ClientWriter.main( libraryClientConfig )
  File "/root/workspace/ROCm/Tensile/repo/Tensile/ClientWriter.py", line 92, in main
    shutil_copy(
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/root/workspace/ROCm/Tensile/repo/Tensile/Source/SolutionMapper.h'
root@x:~/workspace/ROCm/Tensile/dgemm_007-9-asm#
```

**Comment by benjaminulmer** [comment]
Fixed in #1419
