### ISSUE TITLE
‘JoinParameters’ is no longer supported

### ISSUE THREAD

**Issue by flint-stone** [ROCmSoftwarePlatform/Tensile#1479]
Hello! We are trying to test a quick example provided by configuration provided in the repo. Specifically, we use [this](https://github.com/ROCmSoftwarePlatform/Tensile/blob/master/Tensile/Configs/rocblas_sgemm_asm_only.yaml) YAML file and it throws an error saying that JoinParameters is no longer supported. Here is the full trace of the error:

```
# Found  hipcc version 5.0.13601-6b731c37
# Command-line override: CodeObjectVersion
Overriding CodeObjectVersion=V3
Overriding CxxCompiler=hipcc
-- hip::amdhip64 is SHARED_LIBRARY
LLVMObjectYAML_LIBRARY: /opt/rocm/llvm/lib/libLLVMObjectYAML.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/syifan/dev/src/github.com/ROCmSoftwarePlatform/Tensile/build/0_Build
Consolidate compiler generated dependencies of target TensileHost
[ 51%] Built target TensileHost
Consolidate compiler generated dependencies of target TensileClient
[ 95%] Built target TensileClient
Consolidate compiler generated dependencies of target tensile_client
[100%] Built target tensile_client
################################################################################
# Converting Config to BenchmarkProcess Object
################################################################################
# Filling in Parameters With Defaults
Tensile::FATAL: Benchmark step ‘JoinParameters’ is no longer supported
[sudo] password for syifan:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File “/usr/lib/python3.6/subprocess.py”, line 289, in call
    return p.wait(timeout=timeout)
  File “/usr/lib/python3.6/subprocess.py”, line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File “/usr/lib/python3.6/subprocess.py”, line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

```

Meanwhile, I've also tested an earlier version of the code (version 4.31.0) throws a different error with the python code provided:

```
################################################################################
#
#  Tensile v4.31.0
#  Config: /home/lexu/Tensile/repo/Tensile/Configs/rocblas_sgemm_asm_only.yaml
#
################################################################################

# Restoring default globalParameters
# Detected local GPU with ISA: gfx906
# Detected local GPU with ISA: gfx1012
               cap gfx000 gfx803 gfx900 gfx906 gfx908 gfx90a gfx1010 gfx1011 gfx1012 gfx1030 
   HasMFMA_bf16_1k      0      0      0      0      0      1       0       0       0       0 
        HasAddLshl      0      0      1      1      1      1       1       1       1       1 
      HasAtomicAdd      0      0      0      0      1      1       0       0       0       0 
   HasCodeObjectV3      0      1      1      1      1      1       1       1       1       1 
    HasDirectToLds      0      1      1      1      1      1       1       1       1       1 
     HasExplicitCO      0      0      1      1      1      1       1       1       1       1 
     HasExplicitNC      0      0      0      0      0      0       1       1       1       1 
         HasLshlOr      0      0      1      1      1      1       1       1       1       1 
           HasMFMA      0      0      0      0      1      1       0       0       0       0 
         HasSMulHi      0      0      1      1      1      1       1       1       1       1 
        MaxLgkmcnt      1      1      1      1      1      1       1       1       1       1 
          MaxVmcnt      0      1      1      1      1      1       1       1       1       1 
      SupportedISA      0      1      1      1      1      1       1       1       1       1 
   SupportedSource      1      1      1      1      1      1       1       1       1       1 
    v_dot2_f32_f16      0      0      0      1      1      1       0       1       1       1 
   v_dot2c_f32_f16      0      0      0      0      1      1       0       1       1       1 
         v_fma_f16      0      0      1      1      1      1       1       1       1       1 
        v_fmac_f16      0      0      0      0      0      0       0       0       0       0 
         v_mac_f16      0      1      1      1      1      1       0       0       0       0 
      v_pk_fma_f16      0      0      1      1      1      1       1       1       1       1 
     v_pk_fmac_f16      0      0      0      0      0      0       0       0       0       0 
         v_fma_f32      0      1      1      1      1      1       1       1       1       1 
     v_fma_mix_f32      0      0      0      1      1      1       1       1       1       1 
        v_fmac_f32      0      0      0      1      1      1       1       1       1       1 
         v_mac_f32      0      1      1      1      1      1       1       1       1       0 
     v_mad_mix_f32      0      0      1      0      0      0       0       0       0       0 
       HasMFMA_f64      0      0      0      0      0      1       0       0       0       0 
     v_dot4_i32_i8      0      0      0      0      0      0       0       0       0       0 
    v_dot4c_i32_i8      0      0      0      0      1      1       0       1       1       1 
ArchAccUnifiedRegs      0      0      0      0      0      1       0       0       0       0 
    CMPXWritesSGPR      1      1      1      1      1      1       0       0       0       0 
          HasAccCD      0      0      0      0      0      1       0       0       0       0 
        HasEccHalf      0      0      0      1      1      1       0       0       0       0 
         HasWave32      0      0      0      0      0      0       1       1       1       1 
     SeparateVscnt      0      0      0      0      0      0       1       1       1       1 
  Waitcnt0Disabled      0      0      0      0      1      1       0       0       0       0 
# Found  hipcc version 5.0.13601-6b731c37
# Command-line override: CodeObjectVersion

Overriding CodeObjectVersion=V3
Overriding CxxCompiler=hipcc
-- hip::amdhip64 is SHARED_LIBRARY
LLVMObjectYAML_LIBRARY: /opt/rocm/llvm/lib/libLLVMObjectYAML.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lexu/Tensile/Tensile-rocm-5.0.0/build/0_Build
Consolidate compiler generated dependencies of target TensileHost
[ 51%] Built target TensileHost
Consolidate compiler generated dependencies of target TensileClient
[ 95%] Built target TensileClient
Consolidate compiler generated dependencies of target tensile_client
[100%] Built target tensile_client

################################################################################
# Converting Config to BenchmarkProcess Object
################################################################################

# Filling in Parameters With Defaults
# Convert Parameters to Steps
# Benchmark Common Parameters
# Fork Parameters
# Benchmark Fork Parameters
# Join Parameters
# Benchmark Join Parameters
# Benchmark Final
# NumBenchmarkSteps: 2

################################################################################
# Done Creating BenchmarkProcess Object
################################################################################
# Empty winners - use fast initialization of hardcodedParameters


################################################################################
# BenchmarkStep: Cijk_Ailk_Bljk_SB_00 - 00_BenchmarkFork 7.978s
# NumProblems: 1
# BenchmarkParameters:
#     BenchmarkFork = { 0 }
Traceback (most recent call last):
  File "../Tensile/bin/Tensile", line 36, in <module>
    Tensile.main()
  File "/home/lexu/Tensile/Tensile-rocm-5.0.0/Tensile/Tensile.py", line 282, in main
    Tensile(sys.argv[1:])
  File "/home/lexu/Tensile/Tensile-rocm-5.0.0/Tensile/Tensile.py", line 239, in Tensile
    executeStepsInConfig(config)
  File "/home/lexu/Tensile/Tensile-rocm-5.0.0/Tensile/Tensile.py", line 51, in executeStepsInConfig
    BenchmarkProblems.main( config["BenchmarkProblems"] )
  File "/home/lexu/Tensile/Tensile-rocm-5.0.0/Tensile/BenchmarkProblems.py", line 867, in main
    problemSizeGroupConfig, problemSizeGroupIdx)
  File "/home/lexu/Tensile/Tensile-rocm-5.0.0/Tensile/BenchmarkProblems.py", line 229, in benchmarkProblemType
    benchmarkPermutations = constructForkPermutations(benchmarkStep.benchmarkParameters)
  File "/home/lexu/Tensile/Tensile-rocm-5.0.0/Tensile/BenchmarkStructs.py", line 77, in constructForkPermutations
    values = param[name]
TypeError: string indices must be integers
[sudo] password for lexu: 


======================= ROCm System Management Interface =======================
================================= Reset Clocks =================================
GPU[0]		: OverDrive set to 0
GPU[0]		: Successfully reset clocks
GPU[0]		: Performance level reset to auto
============================= End of ROCm SMI Log ==============================


======================= ROCm System Management Interface =======================
============================== Set GPU Fan Speed ===============================
GPU[0]		: Successfully set fan speed to level 50
================================================================================
============================= End of ROCm SMI Log ==============================

```

Is this something that is caused by incompatible version of the code or does this error originated from some other issues? Thanks in advance!

**Comment by syifan** [comment]
Here is some more detailed information about the environment we are trying. 

ROCm version: 5.0.0
GPUs: Radeon VII + RX5500XT, but we only care about the Radeon VII. 
Tensile Version: The current commit on the master branch. Commit ID is [d5eea38](https://github.com/ROCmSoftwarePlatform/Tensile/commit/d5eea381c452c254747f7ba75f2d97472109e395)

Let me know if you need more information.

**Comment by babakpst** [comment]
Hi, Thanks for reporting the issue, and sorry about the inconvenience.  
As the message says, Tensile is no longer supporting JoinParameter (and a few more parameters). I adjusted the first ProblemType of your yaml file, as follows, to run on the latest version of Tensile (using a different architecture though). You can also refer to Configs/rocblas_sgemm_??_inc1_asm_full.yaml to get ideas on how to define the yaml files for the newer version of Tensile. 
We encourage you to use the latest version of Tensile/rocBLAS. Please also refer to the updated document, where I added some more info for the newer version of Tensile at  https://github.com/ROCmSoftwarePlatform/Tensile/tree/master/tuning_docs

Let me know if that solves the issue. 

=================
GlobalParameters:
  MinimumRequiredVersion: 4.4.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 5
  SyncsPerBenchmark: 3
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: False
  Platform: 0
  Device: 0
  KernelTime: True
  #PinClocks: True
  SleepPercent: 0
  DataInitTypeBeta : 0
  PrintWinnersOnly: 0

BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        #- ProblemSizes:
        #  - Exact: [ 5504, 5504, 1, 3104 ]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - PrefetchGlobalRead: [False, True]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 8, 4 ]
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [ 8, 8, 4 ]
        - WorkGroupMapping: [1, 8]
        #- GlobalSplitU: [1, 2, 4, 8]
        - GlobalSplitU: [1]
        - DepthU: [ 8, 16, 32 ]
        - VectorWidth: [-1, 1]
      BenchmarkForkParameters:
      #JoinParameters:
        #- MacroTile
        #- GlobalSplitU
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          #- Range: [ [64, 64, 64, 7000], [64, 64, 64, 7000], [1], [256, 512, 512, 4096] ]
          - Exact: [ 5504, 5504, 1, 3104 ]


#LibraryLogic:
#   ScheduleName: "vega20"
#   DeviceNames: ["Device 66a0", "Device 66a1", "Device 66a7", "Device 66af", "Vega 20"]
#   ArchitectureName: "gfx906"

#    ScheduleName: "navi10"
#    DeviceNames: ["Device 731f"]
#    ArchitectureName: "gfx1010"

    #ScheduleName: "vega10"
    #DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860",
    #              "Device 6861", "Vega 10 XTX [Radeon Vega Frontier Edition]",
    #              "Vega [Radeon RX Vega]", "Vega 10 [Radeon Instinct MI25]",
    #              "Vega", "Device 6864", "Device 686c"]
    #ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

#LibraryClient:

**Comment by babakpst** [comment]
Hi, Thanks for reporting the issue, and sorry about the inconvenience.  
As the message says, Tensile is no longer supporting JoinParameter (and a few more parameters). I adjusted the first ProblemType of your yaml file, as follows, to run on the latest version of Tensile (using a different architecture though). You can also refer to Configs/rocblas_sgemm_??_inc1_asm_full.yaml to get ideas on how to define the yaml files for the newer version of Tensile. 
We encourage you to use the latest version of Tensile/rocBLAS. Please also refer to the updated document, where I added some more info for the newer version of Tensile at  https://github.com/ROCmSoftwarePlatform/Tensile/tree/master/tuning_docs

Let me know if that solves the issue.

**Comment by babakpst** [comment]
[updatedl.txt](https://github.com/ROCmSoftwarePlatform/Tensile/files/8219437/updatedl.txt)

**Comment by babakpst** [comment]
@flint-stone @syifan

**Comment by babakpst** [comment]
@flint-stone @syifan Hopefully, my explanation was enough to solve the issue. Please open/report a new issue if you had more questions. I will close this one then.
