### ISSUE TITLE
Tensile 4.8 and great fail to build with Docker

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/Tensile#482]
When building the docker for MIOpen we are getting this error when building rocBLAS:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/rocm/cget/build/tmp-0ad16ebbc1bd491da0f635bafc5f0437/build/virtualenv/lib/python2.7/site-packages//Tensile/TensileCreateLibrary.py", line 67, in processKernelSourceChunk
    results.append (processKernelSource(kernel, kernelWriterSource, kernelWriterAssembly)) # returns err, src, header, kernelName
  File "/opt/rocm/cget/build/tmp-0ad16ebbc1bd491da0f635bafc5f0437/build/virtualenv/lib/python2.7/site-packages//Tensile/TensileCreateLibrary.py", line 46, in processKernelSource
    (err, src) = kernelWriter.getSourceFileString(kernel)
  File "/opt/rocm/cget/build/tmp-0ad16ebbc1bd491da0f635bafc5f0437/build/virtualenv/lib/python2.7/site-packages/Tensile/KernelWriter.py", line 2141, in getSourceFileString
    (error, kb) = self.kernelBody( kernel, tensorParametersA, tensorParametersB)
  File "/opt/rocm/cget/build/tmp-0ad16ebbc1bd491da0f635bafc5f0437/build/virtualenv/lib/python2.7/site-packages/Tensile/KernelWriter.py", line 659, in kernelBody
    self.makeSchedule(kernel, tensorParametersA, tensorParametersB, localWriteEndIter)
  File "/opt/rocm/cget/build/tmp-0ad16ebbc1bd491da0f635bafc5f0437/build/virtualenv/lib/python2.7/site-packages/Tensile/KernelWriter.py", line 78, in makeSchedule
    maxVmcnt = globalParameters["AsmCaps"][currentIsa]["MaxVmcnt"]
KeyError: 'MaxVmcnt'
```

The error appears when we attempt to build for rocBLAS 2.1.0 and 2.2.0, but not 2.0.0 and earlier.

The Tensile which does seem to build is:
` set( tensile_tag v4.7.0 CACHE STRING "Tensile tag to download" )`
from rocBLAS 2.0.0. 

Here is a link to our dockerfile:
https://github.com/AMDComputeLibraries/MLOpen/blob/develop/Dockerfile

The base install for our CI is ROCm 1.9.2.

We are not sure why this would be the case. What is MaxVmcnt?

**Comment by yxsamliu** [comment]
we saw the same issue. our build machine does not have gpu. maybe it is related to that.

**Comment by daniellowell** [comment]
It may he since the docker build doesn't necessarily know there is a gpu or not? There are gpus on the system however. Has a JIRA been opened for this issue?
