### ISSUE TITLE
 '/opt/rocm/bin/hcc-config' path hardcoded in Tensile

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/Tensile#551]
When building tensile in a docker we have the below error:
`FileNotFoundError: [Errno 2] No such file or directory: '/opt/rocm/bin/hcc-config'`

In a docker this does not work since we are using a linked path not the system linked path.
Tensile can instead use the `/opt/rocm/hcc/bin/hcc-config` path where is where the actual binary is installed.

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/cget/build/tmp-30667e2aac3647f982bfccb12d2861d4/build/virtualenv/bin/TensileCreateLibrary", line 10, in <module>
    sys.exit(TensileCreateLibrary())
  File "/usr/local/cget/build/tmp-30667e2aac3647f982bfccb12d2861d4/build/virtualenv/lib/python3.5/site-packages/Tensile/TensileCreateLibrary.py", line 993, in TensileCreateLibrary
    kernelWriterSource, kernelWriterAssembly)
  File "/usr/local/cget/build/tmp-30667e2aac3647f982bfccb12d2861d4/build/virtualenv/lib/python3.5/site-packages/Tensile/TensileCreateLibrary.py", line 299, in writeSolutionsAndKernels
    codeObjectFiles += buildSourceCodeObjectFiles(kernelFiles, kernels + kernelsBetaOnly, outputPath)
  File "/usr/local/cget/build/tmp-30667e2aac3647f982bfccb12d2861d4/build/virtualenv/lib/python3.5/site-packages/Tensile/TensileCreateLibrary.py", line 138, in buildSourceCodeObjectFiles
    method=lambda x: x.starmap)
  File "/usr/local/cget/build/tmp-30667e2aac3647f982bfccb12d2861d4/build/virtualenv/lib/python3.5/site-packages/Tensile/Common.py", line 1133, in ParallelMap
    rv = mapFunc(function, objects)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value

FileNotFoundError: [Errno 2] No such file or directory: '/opt/rocm/bin/hcc-config'

CMake Error at /usr/local/cget/build/tmp-30667e2aac3647f982bfccb12d2861d4/build/virtualenv/cmake/TensileConfig.cmake:87 (message):
  Error generating kernels
Call Stack (most recent call first):
  library/src/CMakeLists.txt:41 (TensileCreateLibrary)
```

**Comment by daniellowell** [comment]
Offending line:
https://github.com/ROCmSoftwarePlatform/Tensile/blob/85745b01ae2462e4e1d89822bc12f82a3a0c3b16/Tensile/TensileCreateLibrary.py#L112
