### ISSUE TITLE
Something in Python is wrong while generating kernels

### ISSUE THREAD

**Issue by notcome** [ROCmSoftwarePlatform/Tensile#950]
I am having the following output:

```
Reading logic files: Done.
[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 100% (14.2 secs elapsed)
# Writing Custom CMake
# Writing Kernels...
Generating kernels: Launching 48 threads...
info: growing pool += 1 * 2 for GlobalWrite

0         1   
01234567890123
....#######|..
0         1     
0123456789012345
....#######|..||
info: growing pool += 1 * 2 for GlobalWrite

0         1   
01234567890123
....#######|..
0         1     
0123456789012345
....#######|..||
info: growing pool += 1 * 2 for GlobalWrite

0         1   
01234567890123
....#######|..
0         1     
0123456789012345
....#######|..||
info: growing pool += 1 * 2 for GlobalWrite

0         1   
01234567890123
....#######|..
0         1     
0123456789012345
....#######|..||
Generating kernels: Done.
Compiling source kernels: Launching 48 threads...
Traceback (most recent call last):
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/Common.py", line 1371, in apply_print_exception
    return func(*args)
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 146, in buildSourceCodeObjectFile
    hipFlags += subprocess.check_output([which('hipconfig'), '-C']).decode().split(' ')
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1583, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/Common.py", line 1371, in apply_print_exception
    return func(*args)
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 146, in buildSourceCodeObjectFile
    hipFlags += subprocess.check_output([which('hipconfig'), '-C']).decode().split(' ')
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1583, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary", line 38, in <module>
    TensileCreateLibrary()
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 1165, in TensileCreateLibrary
    codeObjectFiles = writeSolutionsAndKernels(outputPath, CxxCompiler, problemTypes, solutions,
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 409, in writeSolutionsAndKernels
    codeObjectFiles += buildSourceCodeObjectFiles(CxxCompiler, kernelFiles, outputPath)
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 211, in buildSourceCodeObjectFiles
    coFiles = Common.ParallelMap(buildSourceCodeObjectFile, args, "Compiling source kernels",
  File "/home/selveskii/rocm-arch/rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/Common.py", line 1441, in ParallelMap
    rv = mapFunc(function, objects)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I am not sure if this is related by my Python version being 3.8.

I am building `Tensile` as a part of building `rocblas`, on Arch Linux, using a modified AUR file:

```
  mkdir -p "$srcdir/build"
  cd "$srcdir/build"

  # fix broken build with stack protection
  export CFLAGS="$(sed -e 's/-fstack-protector-strong//' <<< "$CFLAGS")"
  export CXXFLAGS="$(sed -e 's/-fstack-protector-strong//' <<< "$CXXFLAGS")"
  export CPPFLAGS="$(sed -e 's/-fstack-protector-strong//' <<< "$CPPFLAGS")"

  # compile with HCC
  export CXX="/opt/rocm/hcc/bin/hcc"

  # TODO: fix librocblas.so, it contains references to $srcdir
  cmake -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/rocm/rocblas \
        -HIP_DIR=/opt/rocm/hip/lib/cmake/hip \
        -hcc_DIR=/opt/rocm/hcc/lib/cmake/hcc \
        -Damd_comgr_DIR=/opt/rocm/lib/cmake/amd_comgr \
        -DTensile_ARCHITECTURE=gfx906 \
        -DTensile_LOGIC=asm_full \
        -DBUILD_WITH_TENSILE=ON \
        "$srcdir/rocBLAS-rocm-$_pkgver"
  make
```

**Comment by notcome** [comment]
I think I don't have hipconfig, so the following failed:

```
hipFlags += subprocess.check_output([which('hipconfig'), '-C']).decode().split(' ')
```

**Comment by notcome** [comment]
Okay, I should adjust my path variable to include `hipconfig` at `/opt/rocm/hip/bin/`
